name: Python Project Workflow

on: 
  pull_request:
    types:
      - edited
      - opened
      - reopened

    branches:
      - main
      - master
      - dev

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    
    - name: Lint with Ruff
      uses: astral-sh/ruff-action@0c50076f12c38c3d0115b7b519b54a91cb9cf0ad
      with:
        version: "0.12.3"

  bandit: 
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

    - name: Perform Bandit analysis
      uses: PyCQA/bandit-action@8a1b30610f61f3f792fe7556e888c9d7dffa52de